repos:
  - repo: local
    hooks:
      - id: java-static-analysis
        name: Java static analysis
        entry: ./scripts/run-static-analysis.sh
        language: script
        pass_filenames: false
