#syntax=docker/dockerfile:1.7-labs
# build factgraph since it will be a dependency in share-libs-builder
FROM sbtscala/scala-sbt:eclipse-temurin-alpine-21.0.2_13_1.9.9_3.3.3 AS factgraph-builder
WORKDIR /build/
COPY --from=factgraph-repo js/src/ js/src/
COPY --from=factgraph-repo jvm/src/ jvm/src/
COPY --from=factgraph-repo project/build.properties project/plugins.sbt project/
COPY --from=factgraph-repo shared/ shared/
COPY --from=factgraph-repo build.sbt .
RUN sbt compile package publishM2

# build shared dependencies
FROM eclipse-temurin:21-jdk-alpine AS shared-dependencies-builder
COPY --from=factgraph-builder /root/.m2/repository/gov/irs/factgraph/fact-graph_3/ /root/.m2/repository/gov/irs/factgraph/fact-graph_3/
ARG MAVEN_OPTS=""
WORKDIR /build/
COPY --from=config . ./config/
COPY --from=boms . ./boms/
WORKDIR /build/libs/
COPY --from=shared-libs .mvn/wrapper/maven-wrapper.properties .mvn/wrapper/
COPY --from=shared-libs mvnw ./
COPY --from=shared-libs --parents **/pom.xml ./
RUN ./mvnw dependency:resolve -P resolve
COPY --from=shared-libs starters/ ./starters/
COPY --from=shared-libs data-models/ ./data-models/
RUN ./mvnw install

FROM shared-dependencies-builder AS mef-submit-builder
ARG MAVEN_OPTS=""
ENV MEF_REPO /mef-client-sdk
ENV A2A_TOOLKIT_HOME /${MEF_REPO}/MeF_Client_SDK/Java/source/
COPY --from=mef-sdk-repo MeF_Client_SDK/ /${MEF_REPO}/MeF_Client_SDK/
COPY --from=config . /config/
WORKDIR /build/
COPY --from=scripts install-mef-sdk.sh .
COPY mvnw pom.xml ./
COPY .mvn/wrapper/maven-wrapper.properties .mvn/wrapper/
RUN ./install-mef-sdk.sh
RUN ./mvnw dependency:resolve
COPY src/ /build/src/
RUN ./mvnw package

FROM eclipse-temurin:21-jre-alpine
COPY --from=mef-submit-builder /build/target/mef-submit-0.0.1-SNAPSHOT.jar /app.jar
COPY --from=mef-sdk-repo MeF_Client_SDK/Java/source/ /mef-client-sdk-src/
# Run from dir that allows mef-sdk to write it's files to the working directory (next iteration: configure mef-sdk)
# Pre-create `/mef-data`, the prefix used in the Spring profile `application-docker.yaml` (`submit.directories.*`)# Pre-create `/mef-data`, the prefix used in the Spring profile `application-docker.yaml` (`submit.directories.*`)
RUN adduser --system --no-create-home jar-runner && \
    mkdir -p /mef-data && \
    mkdir -p /jar-run && \
    chown jar-runner /mef-data /jar-run
WORKDIR /jar-run
USER jar-runner
CMD ["java", "-jar", "/app.jar"]
