package gov.irs.directfile.api.dataimport.gating;

public enum DataImportBehavior {
    DATA_IMPORT_ABOUT_YOU_BASIC,
    DATA_IMPORT_ABOUT_YOU_BASIC_PLUS_IP_PIN,
    DATA_IMPORT_ABOUT_YOU_BASIC_PLUS_IP_PIN_PLUS_W2,
    DATA_IMPORT_ABOUT_YOU_BASIC_PLUS_IP_PIN_PLUS_W2_PLUS_1099_INT,
    DATA_IMPORT_ABOUT_YOU_BASIC_PLUS_IP_PIN_PLUS_W2_PLUS_1099_INT_PLUS_1095_A;
}
