###
# Data Import
# Note: Log in via CSP Simulator 
GET http://localhost:8080/df/file/api/v1/taxreturns/d5efc7b7-11c1-4250-ab70-0a3884a8688e/populate
SM_UNIVERSALID: d5efc7b7-11c1-4250-ab70-0a3884a8688e
x-data-import-profile: homer

###
GET http://localhost:8080/df/file/api/v1/taxreturns/d5efc7b7-11c1-4250-ab70-0a3884a8688e/populate
SM_UNIVERSALID: d5efc7b7-11c1-4250-ab70-0a3884a8688e
x-data-import-profile: marge
x-data-import-dob: [1976,1,1]

