package gov.irs.directfile.status.mef.client;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import gov.irs.mef.services.ServiceContext;

@Getter
@Setter
@AllArgsConstructor
@SuppressFBWarnings(
        value = {"EI_EXPOSE_REP", "EI_EXPOSE_REP2"},
        justification = "The Getter and Setter are auto-generated by Lombox.")
public class ServiceContextWrapper {
    private final ServiceContext serviceContext;
}
