#syntax=docker/dockerfile:1.7-labs
# Note: This uses some relatively new features, so make sure docker is
#       up-to-date on your system or this build may fail

# 1. build factgraph
# For this step to work, you must define `factgraph-repo` in either your
# docker-compose.yaml's `additional_contexts` or from the command line with
# `docker buildx build --build-context factgraph-repo=/some/path [other args]`
FROM sbtscala/scala-sbt:eclipse-temurin-alpine-21.0.2_13_1.9.9_3.3.3 AS factgraph-builder
WORKDIR /build/
COPY --from=factgraph-repo js/src/ js/src/
COPY --from=factgraph-repo jvm/src/ jvm/src/
COPY --from=factgraph-repo project/build.properties project/plugins.sbt project/
COPY --from=factgraph-repo shared/ shared/
COPY --from=factgraph-repo build.sbt .
RUN sbt compile package publishM2

# 2. build shared dependencies
FROM eclipse-temurin:21-jdk-alpine AS shared-dependencies-builder
COPY --from=factgraph-builder /root/.m2/repository/gov/irs/factgraph/fact-graph_3/ /root/.m2/repository/gov/irs/factgraph/fact-graph_3/
ARG MAVEN_OPTS=""
WORKDIR /build/
COPY --from=config . ./config/
COPY --from=boms . ./boms/
WORKDIR /build/libs/
COPY --from=shared-libs .mvn/wrapper/maven-wrapper.properties .mvn/wrapper/
COPY --from=shared-libs mvnw ./
COPY --from=shared-libs --parents **/pom.xml ./
RUN ./mvnw dependency:resolve -P resolve
COPY --from=shared-libs starters/ ./starters/
COPY --from=shared-libs data-models/ ./data-models/
RUN ./mvnw install

# 5. build backend spring api
FROM shared-dependencies-builder AS api-builder
ARG MAVEN_OPTS=""
ENV MEF_REPO /mef-repo
COPY --from=config . /config/
WORKDIR /build/
COPY mvnw ./
COPY .mvn/wrapper/maven-wrapper.properties .mvn/wrapper/
COPY pom.xml ./
RUN ./mvnw dependency:resolve
# copy source tree after dependency resolution so source changes don't force re-download of all dependencies
COPY src/ /build/src/
RUN ./mvnw package

# 6. bundle backend api jar into runnable image
FROM eclipse-temurin:21-jre-alpine
ENV SPRING_PROFILES_ACTIVE=development
COPY --from=api-builder /build/target/directfile-api-0.0.1-SNAPSHOT.jar /app.jar
RUN adduser --system --no-create-home jar-runner
USER jar-runner
CMD ["java", "-jar", "/app.jar"]
